[[watch]]
name = "data"
paths = ["/data"]
recursive = false

[[watch]]
name = "test"
paths = ["/test"]
recursive = false

[[plugin]]
name = "transcribe"
priority = 10

[[plugin]]
name = "pdf-parser"
priority = 20
